;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-copy-from-below
        evil-delete
        evil-delete-backward-word
        evil-delete-char
        evil-find-char
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-paste-last-insertion
        evil-previous-line
        evil-scroll-line-down
        evil-substitute
        evil-visual-char
        indent-for-tab-command
        multiple-cursors-mode
        undo-redo
        ))

(setq mc/cmds-to-run-once
      '(
        evil-scroll-down
        evil-undo
        ))
